# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Haotao's website
url: "http://laihaotao.me"

twitter_username: jekyllrb
github_username:  laihaotao

# Disqus settings
# disqus_username: laihaotao

# Build settings
markdown: kramdown
kramdown:
  
  # input source respects GitHub Favourite Markdown format
  input: GFM
  
  # how to use rouge?
  #   gem install rouge                       => install rouge
  #   rougify help style                      => list all available theme
  #   rougify style base16.dart > ./hl.css    => generate stylesheet file
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
      
  

theme: minima
plugins:
  - jekyll-feed 
  - jekyll-paginate
  # - jekyll-paginate-v2

paginate: 10
paginate_path: "archive/page:num"

# Pagination Settings
# pagination:
#   enabled: true
#   per_page: 10
#   permalink: '/page/:num/'
#   title: ' - page :num'
#   limit: 0
#   sort_field: 'date'
#   sort_reverse: true
#   indexpage: 'archive'
#   collection: 'posts'


# Gobal setting
user:
  name_zh: Haotao Lai
  name_en: Eric
  status: looking for internship
  description: Master Student in Computer Science @ Concordia

  contact_en: You are welcome to contact me with any problem, I will reply you ASAP.
  contact_zh: 欢迎通过下面的方式和我取得联系, 我会尽快回复您.

  university_mail: h_lai@encs.concordia.ca
  personal_mail: haotao.lai@gmail.com

# Page registration
page_names:
  - home
  - archive
  - about
  - contact
  - ta
  # - tags

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
